version: '3'
services:
  gameserver:
    build: ./server
    ports:
      - "5000:5000"
  videoserver:
    build: ./videoserver
    ports:
      - "5004:5004"
  frontend:
    build: ./client
    ports:
      - "5003:80"
