// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

#include "internal.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace webcamshooting {
PROTOBUF_CONSTEXPR DamageInternal::DamageInternal(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.damagedby_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.amount_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DamageInternalDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DamageInternalDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DamageInternalDefaultTypeInternal() {}
  union {
    DamageInternal _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DamageInternalDefaultTypeInternal _DamageInternal_default_instance_;
}  // namespace webcamshooting
static ::_pb::Metadata file_level_metadata_internal_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_internal_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_internal_2eproto = nullptr;

const uint32_t TableStruct_internal_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::webcamshooting::DamageInternal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::webcamshooting::DamageInternal, _impl_.damagedby_),
  PROTOBUF_FIELD_OFFSET(::webcamshooting::DamageInternal, _impl_.amount_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::webcamshooting::DamageInternal)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::webcamshooting::_DamageInternal_default_instance_._instance,
};

const char descriptor_table_protodef_internal_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016internal.proto\022\016webcamshooting\"3\n\016Dama"
  "geInternal\022\021\n\tdamagedBy\030\001 \001(\t\022\016\n\006amount\030"
  "\002 \001(\002B0Z.github.com/kanicreampasta/webca"
  "mshooting/typesb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_internal_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_internal_2eproto = {
    false, false, 143, descriptor_table_protodef_internal_2eproto,
    "internal.proto",
    &descriptor_table_internal_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_internal_2eproto::offsets,
    file_level_metadata_internal_2eproto, file_level_enum_descriptors_internal_2eproto,
    file_level_service_descriptors_internal_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_internal_2eproto_getter() {
  return &descriptor_table_internal_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_internal_2eproto(&descriptor_table_internal_2eproto);
namespace webcamshooting {

// ===================================================================

class DamageInternal::_Internal {
 public:
};

DamageInternal::DamageInternal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:webcamshooting.DamageInternal)
}
DamageInternal::DamageInternal(const DamageInternal& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DamageInternal* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.damagedby_){}
    , decltype(_impl_.amount_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.damagedby_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.damagedby_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_damagedby().empty()) {
    _this->_impl_.damagedby_.Set(from._internal_damagedby(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.amount_ = from._impl_.amount_;
  // @@protoc_insertion_point(copy_constructor:webcamshooting.DamageInternal)
}

inline void DamageInternal::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.damagedby_){}
    , decltype(_impl_.amount_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.damagedby_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.damagedby_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DamageInternal::~DamageInternal() {
  // @@protoc_insertion_point(destructor:webcamshooting.DamageInternal)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DamageInternal::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.damagedby_.Destroy();
}

void DamageInternal::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DamageInternal::Clear() {
// @@protoc_insertion_point(message_clear_start:webcamshooting.DamageInternal)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.damagedby_.ClearToEmpty();
  _impl_.amount_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DamageInternal::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string damagedBy = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_damagedby();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "webcamshooting.DamageInternal.damagedBy"));
        } else
          goto handle_unusual;
        continue;
      // float amount = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.amount_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DamageInternal::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:webcamshooting.DamageInternal)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string damagedBy = 1;
  if (!this->_internal_damagedby().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_damagedby().data(), static_cast<int>(this->_internal_damagedby().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "webcamshooting.DamageInternal.damagedBy");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_damagedby(), target);
  }

  // float amount = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_amount = this->_internal_amount();
  uint32_t raw_amount;
  memcpy(&raw_amount, &tmp_amount, sizeof(tmp_amount));
  if (raw_amount != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_amount(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:webcamshooting.DamageInternal)
  return target;
}

size_t DamageInternal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:webcamshooting.DamageInternal)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string damagedBy = 1;
  if (!this->_internal_damagedby().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_damagedby());
  }

  // float amount = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_amount = this->_internal_amount();
  uint32_t raw_amount;
  memcpy(&raw_amount, &tmp_amount, sizeof(tmp_amount));
  if (raw_amount != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DamageInternal::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DamageInternal::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DamageInternal::GetClassData() const { return &_class_data_; }


void DamageInternal::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DamageInternal*>(&to_msg);
  auto& from = static_cast<const DamageInternal&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:webcamshooting.DamageInternal)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_damagedby().empty()) {
    _this->_internal_set_damagedby(from._internal_damagedby());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_amount = from._internal_amount();
  uint32_t raw_amount;
  memcpy(&raw_amount, &tmp_amount, sizeof(tmp_amount));
  if (raw_amount != 0) {
    _this->_internal_set_amount(from._internal_amount());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DamageInternal::CopyFrom(const DamageInternal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:webcamshooting.DamageInternal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DamageInternal::IsInitialized() const {
  return true;
}

void DamageInternal::InternalSwap(DamageInternal* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.damagedby_, lhs_arena,
      &other->_impl_.damagedby_, rhs_arena
  );
  swap(_impl_.amount_, other->_impl_.amount_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DamageInternal::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_internal_2eproto_getter, &descriptor_table_internal_2eproto_once,
      file_level_metadata_internal_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace webcamshooting
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::webcamshooting::DamageInternal*
Arena::CreateMaybeMessage< ::webcamshooting::DamageInternal >(Arena* arena) {
  return Arena::CreateMessageInternal< ::webcamshooting::DamageInternal >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
