// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_internal_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_internal_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_internal_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_internal_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_internal_2eproto;
namespace webcamshooting {
class DamageInternal;
struct DamageInternalDefaultTypeInternal;
extern DamageInternalDefaultTypeInternal _DamageInternal_default_instance_;
}  // namespace webcamshooting
PROTOBUF_NAMESPACE_OPEN
template<> ::webcamshooting::DamageInternal* Arena::CreateMaybeMessage<::webcamshooting::DamageInternal>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace webcamshooting {

// ===================================================================

class DamageInternal final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:webcamshooting.DamageInternal) */ {
 public:
  inline DamageInternal() : DamageInternal(nullptr) {}
  ~DamageInternal() override;
  explicit PROTOBUF_CONSTEXPR DamageInternal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DamageInternal(const DamageInternal& from);
  DamageInternal(DamageInternal&& from) noexcept
    : DamageInternal() {
    *this = ::std::move(from);
  }

  inline DamageInternal& operator=(const DamageInternal& from) {
    CopyFrom(from);
    return *this;
  }
  inline DamageInternal& operator=(DamageInternal&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DamageInternal& default_instance() {
    return *internal_default_instance();
  }
  static inline const DamageInternal* internal_default_instance() {
    return reinterpret_cast<const DamageInternal*>(
               &_DamageInternal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DamageInternal& a, DamageInternal& b) {
    a.Swap(&b);
  }
  inline void Swap(DamageInternal* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DamageInternal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DamageInternal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DamageInternal>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DamageInternal& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DamageInternal& from) {
    DamageInternal::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DamageInternal* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "webcamshooting.DamageInternal";
  }
  protected:
  explicit DamageInternal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDamagedByFieldNumber = 1,
    kAmountFieldNumber = 2,
  };
  // string damagedBy = 1;
  void clear_damagedby();
  const std::string& damagedby() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_damagedby(ArgT0&& arg0, ArgT... args);
  std::string* mutable_damagedby();
  PROTOBUF_NODISCARD std::string* release_damagedby();
  void set_allocated_damagedby(std::string* damagedby);
  private:
  const std::string& _internal_damagedby() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_damagedby(const std::string& value);
  std::string* _internal_mutable_damagedby();
  public:

  // float amount = 2;
  void clear_amount();
  float amount() const;
  void set_amount(float value);
  private:
  float _internal_amount() const;
  void _internal_set_amount(float value);
  public:

  // @@protoc_insertion_point(class_scope:webcamshooting.DamageInternal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr damagedby_;
    float amount_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_internal_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DamageInternal

// string damagedBy = 1;
inline void DamageInternal::clear_damagedby() {
  _impl_.damagedby_.ClearToEmpty();
}
inline const std::string& DamageInternal::damagedby() const {
  // @@protoc_insertion_point(field_get:webcamshooting.DamageInternal.damagedBy)
  return _internal_damagedby();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DamageInternal::set_damagedby(ArgT0&& arg0, ArgT... args) {
 
 _impl_.damagedby_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:webcamshooting.DamageInternal.damagedBy)
}
inline std::string* DamageInternal::mutable_damagedby() {
  std::string* _s = _internal_mutable_damagedby();
  // @@protoc_insertion_point(field_mutable:webcamshooting.DamageInternal.damagedBy)
  return _s;
}
inline const std::string& DamageInternal::_internal_damagedby() const {
  return _impl_.damagedby_.Get();
}
inline void DamageInternal::_internal_set_damagedby(const std::string& value) {
  
  _impl_.damagedby_.Set(value, GetArenaForAllocation());
}
inline std::string* DamageInternal::_internal_mutable_damagedby() {
  
  return _impl_.damagedby_.Mutable(GetArenaForAllocation());
}
inline std::string* DamageInternal::release_damagedby() {
  // @@protoc_insertion_point(field_release:webcamshooting.DamageInternal.damagedBy)
  return _impl_.damagedby_.Release();
}
inline void DamageInternal::set_allocated_damagedby(std::string* damagedby) {
  if (damagedby != nullptr) {
    
  } else {
    
  }
  _impl_.damagedby_.SetAllocated(damagedby, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.damagedby_.IsDefault()) {
    _impl_.damagedby_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:webcamshooting.DamageInternal.damagedBy)
}

// float amount = 2;
inline void DamageInternal::clear_amount() {
  _impl_.amount_ = 0;
}
inline float DamageInternal::_internal_amount() const {
  return _impl_.amount_;
}
inline float DamageInternal::amount() const {
  // @@protoc_insertion_point(field_get:webcamshooting.DamageInternal.amount)
  return _internal_amount();
}
inline void DamageInternal::_internal_set_amount(float value) {
  
  _impl_.amount_ = value;
}
inline void DamageInternal::set_amount(float value) {
  _internal_set_amount(value);
  // @@protoc_insertion_point(field_set:webcamshooting.DamageInternal.amount)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace webcamshooting

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_internal_2eproto
