// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface ClientUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.ClientUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pid = 1;</code>
   * @return The pid.
   */
  java.lang.String getPid();
  /**
   * <code>string pid = 1;</code>
   * @return The bytes for pid.
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>.webcamshooting.Player player = 2;</code>
   * @return Whether the player field is set.
   */
  boolean hasPlayer();
  /**
   * <code>.webcamshooting.Player player = 2;</code>
   * @return The player.
   */
  one.panda_number.wcs.protos.Player getPlayer();
  /**
   * <code>.webcamshooting.Player player = 2;</code>
   */
  one.panda_number.wcs.protos.PlayerOrBuilder getPlayerOrBuilder();

  /**
   * <code>bool fired = 3;</code>
   * @return The fired.
   */
  boolean getFired();

  /**
   * <code>repeated .webcamshooting.Damage damages = 4;</code>
   */
  java.util.List<one.panda_number.wcs.protos.Damage> 
      getDamagesList();
  /**
   * <code>repeated .webcamshooting.Damage damages = 4;</code>
   */
  one.panda_number.wcs.protos.Damage getDamages(int index);
  /**
   * <code>repeated .webcamshooting.Damage damages = 4;</code>
   */
  int getDamagesCount();
  /**
   * <code>repeated .webcamshooting.Damage damages = 4;</code>
   */
  java.util.List<? extends one.panda_number.wcs.protos.DamageOrBuilder> 
      getDamagesOrBuilderList();
  /**
   * <code>repeated .webcamshooting.Damage damages = 4;</code>
   */
  one.panda_number.wcs.protos.DamageOrBuilder getDamagesOrBuilder(
      int index);
}
