// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface DamageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.Damage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pid = 1;</code>
   * @return The pid.
   */
  java.lang.String getPid();
  /**
   * <code>string pid = 1;</code>
   * @return The bytes for pid.
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>float damage = 2;</code>
   * @return The damage.
   */
  float getDamage();
}
