// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface DamageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.DamageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string by = 1;</code>
   * @return The by.
   */
  java.lang.String getBy();
  /**
   * <code>string by = 1;</code>
   * @return The bytes for by.
   */
  com.google.protobuf.ByteString
      getByBytes();

  /**
   * <code>float amount = 2;</code>
   * @return The amount.
   */
  float getAmount();
}
