// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface DeadUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.DeadUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pid = 1;</code>
   * @return The pid.
   */
  java.lang.String getPid();
  /**
   * <code>string pid = 1;</code>
   * @return The bytes for pid.
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>optional string killed_by = 2;</code>
   * @return Whether the killedBy field is set.
   */
  boolean hasKilledBy();
  /**
   * <code>optional string killed_by = 2;</code>
   * @return The killedBy.
   */
  java.lang.String getKilledBy();
  /**
   * <code>optional string killed_by = 2;</code>
   * @return The bytes for killedBy.
   */
  com.google.protobuf.ByteString
      getKilledByBytes();
}
