// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public final class GameProtos {
  private GameProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_Vector3_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_Vector3_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_Damage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_Damage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_ClientUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_ClientUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_JoinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_JoinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_DeadUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_DeadUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_RespawnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_RespawnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_PidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_PidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_DamageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_DamageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_PlayerUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_PlayerUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webcamshooting_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_webcamshooting_UpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngame.proto\022\016webcamshooting\"*\n\007Vector3\022" +
      "\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"%\n\006Dama" +
      "ge\022\013\n\003pid\030\001 \001(\t\022\016\n\006damage\030\002 \001(\002\"z\n\006Playe" +
      "r\022)\n\010position\030\001 \001(\0132\027.webcamshooting.Vec" +
      "tor3\022)\n\010velocity\030\002 \001(\0132\027.webcamshooting." +
      "Vector3\022\013\n\003yaw\030\003 \001(\002\022\r\n\005pitch\030\004 \001(\002\"{\n\014C" +
      "lientUpdate\022\013\n\003pid\030\001 \001(\t\022&\n\006player\030\002 \001(\013" +
      "2\026.webcamshooting.Player\022\r\n\005fired\030\003 \001(\010\022" +
      "\'\n\007damages\030\004 \003(\0132\026.webcamshooting.Damage" +
      "\"\033\n\013JoinRequest\022\014\n\004name\030\001 \001(\t\"?\n\nDeadUpd" +
      "ate\022\013\n\003pid\030\001 \001(\t\022\026\n\tkilled_by\030\002 \001(\tH\000\210\001\001" +
      "B\014\n\n_killed_by\"H\n\016RespawnRequest\022\013\n\003pid\030" +
      "\001 \001(\t\022)\n\010position\030\002 \001(\0132\027.webcamshooting" +
      ".Vector3\"\364\001\n\007Request\0223\n\014join_request\030\001 \001" +
      "(\0132\033.webcamshooting.JoinRequestH\000\0225\n\rcli" +
      "ent_update\030\002 \001(\0132\034.webcamshooting.Client" +
      "UpdateH\000\0221\n\013dead_update\030\003 \001(\0132\032.webcamsh" +
      "ooting.DeadUpdateH\000\0229\n\017respawn_request\030\004" +
      " \001(\0132\036.webcamshooting.RespawnRequestH\000B\017" +
      "\n\rrequest_oneof\"\214\001\n\010Response\0223\n\014pid_resp" +
      "onse\030\001 \001(\0132\033.webcamshooting.PidResponseH" +
      "\000\0229\n\017update_response\030\002 \001(\0132\036.webcamshoot" +
      "ing.UpdateResponseH\000B\020\n\016response_oneof\"\032" +
      "\n\013PidResponse\022\013\n\003pid\030\001 \001(\t\",\n\016DamageResp" +
      "onse\022\n\n\002by\030\001 \001(\t\022\016\n\006amount\030\002 \001(\002\"\231\001\n\024Pla" +
      "yerUpdateResponse\022\013\n\003pid\030\001 \001(\t\022&\n\006player" +
      "\030\002 \001(\0132\026.webcamshooting.Player\022\014\n\004dead\030\003" +
      " \001(\010\022\r\n\005fired\030\006 \001(\010\022/\n\007damages\030\007 \003(\0132\036.w" +
      "ebcamshooting.DamageResponse\"G\n\016UpdateRe" +
      "sponse\0225\n\007players\030\001 \003(\0132$.webcamshooting" +
      ".PlayerUpdateResponseB[\n\033one.panda_numbe" +
      "r.wcs.protosB\nGameProtosP\001Z.github.com/k" +
      "anicreampasta/webcamshooting/typesb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_webcamshooting_Vector3_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webcamshooting_Vector3_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_Vector3_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_webcamshooting_Damage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_webcamshooting_Damage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_Damage_descriptor,
        new java.lang.String[] { "Pid", "Damage", });
    internal_static_webcamshooting_Player_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_webcamshooting_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_Player_descriptor,
        new java.lang.String[] { "Position", "Velocity", "Yaw", "Pitch", });
    internal_static_webcamshooting_ClientUpdate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_webcamshooting_ClientUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_ClientUpdate_descriptor,
        new java.lang.String[] { "Pid", "Player", "Fired", "Damages", });
    internal_static_webcamshooting_JoinRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_webcamshooting_JoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_JoinRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_webcamshooting_DeadUpdate_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_webcamshooting_DeadUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_DeadUpdate_descriptor,
        new java.lang.String[] { "Pid", "KilledBy", "KilledBy", });
    internal_static_webcamshooting_RespawnRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_webcamshooting_RespawnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_RespawnRequest_descriptor,
        new java.lang.String[] { "Pid", "Position", });
    internal_static_webcamshooting_Request_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_webcamshooting_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_Request_descriptor,
        new java.lang.String[] { "JoinRequest", "ClientUpdate", "DeadUpdate", "RespawnRequest", "RequestOneof", });
    internal_static_webcamshooting_Response_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_webcamshooting_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_Response_descriptor,
        new java.lang.String[] { "PidResponse", "UpdateResponse", "ResponseOneof", });
    internal_static_webcamshooting_PidResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_webcamshooting_PidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_PidResponse_descriptor,
        new java.lang.String[] { "Pid", });
    internal_static_webcamshooting_DamageResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_webcamshooting_DamageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_DamageResponse_descriptor,
        new java.lang.String[] { "By", "Amount", });
    internal_static_webcamshooting_PlayerUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_webcamshooting_PlayerUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_PlayerUpdateResponse_descriptor,
        new java.lang.String[] { "Pid", "Player", "Dead", "Fired", "Damages", });
    internal_static_webcamshooting_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_webcamshooting_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_webcamshooting_UpdateResponse_descriptor,
        new java.lang.String[] { "Players", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
