// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

/**
 * Protobuf type {@code webcamshooting.Player}
 */
public final class Player extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:webcamshooting.Player)
    PlayerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Player.newBuilder() to construct.
  private Player(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Player() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Player();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Player(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            one.panda_number.wcs.protos.Vector3.Builder subBuilder = null;
            if (position_ != null) {
              subBuilder = position_.toBuilder();
            }
            position_ = input.readMessage(one.panda_number.wcs.protos.Vector3.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(position_);
              position_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            one.panda_number.wcs.protos.Vector3.Builder subBuilder = null;
            if (velocity_ != null) {
              subBuilder = velocity_.toBuilder();
            }
            velocity_ = input.readMessage(one.panda_number.wcs.protos.Vector3.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(velocity_);
              velocity_ = subBuilder.buildPartial();
            }

            break;
          }
          case 29: {

            yaw_ = input.readFloat();
            break;
          }
          case 37: {

            pitch_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Player_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Player_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            one.panda_number.wcs.protos.Player.class, one.panda_number.wcs.protos.Player.Builder.class);
  }

  public static final int POSITION_FIELD_NUMBER = 1;
  private one.panda_number.wcs.protos.Vector3 position_;
  /**
   * <code>.webcamshooting.Vector3 position = 1;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return position_ != null;
  }
  /**
   * <code>.webcamshooting.Vector3 position = 1;</code>
   * @return The position.
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.Vector3 getPosition() {
    return position_ == null ? one.panda_number.wcs.protos.Vector3.getDefaultInstance() : position_;
  }
  /**
   * <code>.webcamshooting.Vector3 position = 1;</code>
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.Vector3OrBuilder getPositionOrBuilder() {
    return getPosition();
  }

  public static final int VELOCITY_FIELD_NUMBER = 2;
  private one.panda_number.wcs.protos.Vector3 velocity_;
  /**
   * <code>.webcamshooting.Vector3 velocity = 2;</code>
   * @return Whether the velocity field is set.
   */
  @java.lang.Override
  public boolean hasVelocity() {
    return velocity_ != null;
  }
  /**
   * <code>.webcamshooting.Vector3 velocity = 2;</code>
   * @return The velocity.
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.Vector3 getVelocity() {
    return velocity_ == null ? one.panda_number.wcs.protos.Vector3.getDefaultInstance() : velocity_;
  }
  /**
   * <code>.webcamshooting.Vector3 velocity = 2;</code>
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.Vector3OrBuilder getVelocityOrBuilder() {
    return getVelocity();
  }

  public static final int YAW_FIELD_NUMBER = 3;
  private float yaw_;
  /**
   * <code>float yaw = 3;</code>
   * @return The yaw.
   */
  @java.lang.Override
  public float getYaw() {
    return yaw_;
  }

  public static final int PITCH_FIELD_NUMBER = 4;
  private float pitch_;
  /**
   * <code>float pitch = 4;</code>
   * @return The pitch.
   */
  @java.lang.Override
  public float getPitch() {
    return pitch_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (position_ != null) {
      output.writeMessage(1, getPosition());
    }
    if (velocity_ != null) {
      output.writeMessage(2, getVelocity());
    }
    if (java.lang.Float.floatToRawIntBits(yaw_) != 0) {
      output.writeFloat(3, yaw_);
    }
    if (java.lang.Float.floatToRawIntBits(pitch_) != 0) {
      output.writeFloat(4, pitch_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (position_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPosition());
    }
    if (velocity_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getVelocity());
    }
    if (java.lang.Float.floatToRawIntBits(yaw_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, yaw_);
    }
    if (java.lang.Float.floatToRawIntBits(pitch_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, pitch_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof one.panda_number.wcs.protos.Player)) {
      return super.equals(obj);
    }
    one.panda_number.wcs.protos.Player other = (one.panda_number.wcs.protos.Player) obj;

    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (hasVelocity() != other.hasVelocity()) return false;
    if (hasVelocity()) {
      if (!getVelocity()
          .equals(other.getVelocity())) return false;
    }
    if (java.lang.Float.floatToIntBits(getYaw())
        != java.lang.Float.floatToIntBits(
            other.getYaw())) return false;
    if (java.lang.Float.floatToIntBits(getPitch())
        != java.lang.Float.floatToIntBits(
            other.getPitch())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    if (hasVelocity()) {
      hash = (37 * hash) + VELOCITY_FIELD_NUMBER;
      hash = (53 * hash) + getVelocity().hashCode();
    }
    hash = (37 * hash) + YAW_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getYaw());
    hash = (37 * hash) + PITCH_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPitch());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static one.panda_number.wcs.protos.Player parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static one.panda_number.wcs.protos.Player parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Player parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static one.panda_number.wcs.protos.Player parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Player parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static one.panda_number.wcs.protos.Player parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Player parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static one.panda_number.wcs.protos.Player parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Player parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static one.panda_number.wcs.protos.Player parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Player parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static one.panda_number.wcs.protos.Player parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(one.panda_number.wcs.protos.Player prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code webcamshooting.Player}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:webcamshooting.Player)
      one.panda_number.wcs.protos.PlayerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Player_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Player_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              one.panda_number.wcs.protos.Player.class, one.panda_number.wcs.protos.Player.Builder.class);
    }

    // Construct using one.panda_number.wcs.protos.Player.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (positionBuilder_ == null) {
        position_ = null;
      } else {
        position_ = null;
        positionBuilder_ = null;
      }
      if (velocityBuilder_ == null) {
        velocity_ = null;
      } else {
        velocity_ = null;
        velocityBuilder_ = null;
      }
      yaw_ = 0F;

      pitch_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Player_descriptor;
    }

    @java.lang.Override
    public one.panda_number.wcs.protos.Player getDefaultInstanceForType() {
      return one.panda_number.wcs.protos.Player.getDefaultInstance();
    }

    @java.lang.Override
    public one.panda_number.wcs.protos.Player build() {
      one.panda_number.wcs.protos.Player result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public one.panda_number.wcs.protos.Player buildPartial() {
      one.panda_number.wcs.protos.Player result = new one.panda_number.wcs.protos.Player(this);
      if (positionBuilder_ == null) {
        result.position_ = position_;
      } else {
        result.position_ = positionBuilder_.build();
      }
      if (velocityBuilder_ == null) {
        result.velocity_ = velocity_;
      } else {
        result.velocity_ = velocityBuilder_.build();
      }
      result.yaw_ = yaw_;
      result.pitch_ = pitch_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof one.panda_number.wcs.protos.Player) {
        return mergeFrom((one.panda_number.wcs.protos.Player)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(one.panda_number.wcs.protos.Player other) {
      if (other == one.panda_number.wcs.protos.Player.getDefaultInstance()) return this;
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      if (other.hasVelocity()) {
        mergeVelocity(other.getVelocity());
      }
      if (other.getYaw() != 0F) {
        setYaw(other.getYaw());
      }
      if (other.getPitch() != 0F) {
        setPitch(other.getPitch());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      one.panda_number.wcs.protos.Player parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (one.panda_number.wcs.protos.Player) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private one.panda_number.wcs.protos.Vector3 position_;
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.Vector3, one.panda_number.wcs.protos.Vector3.Builder, one.panda_number.wcs.protos.Vector3OrBuilder> positionBuilder_;
    /**
     * <code>.webcamshooting.Vector3 position = 1;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return positionBuilder_ != null || position_ != null;
    }
    /**
     * <code>.webcamshooting.Vector3 position = 1;</code>
     * @return The position.
     */
    public one.panda_number.wcs.protos.Vector3 getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? one.panda_number.wcs.protos.Vector3.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.webcamshooting.Vector3 position = 1;</code>
     */
    public Builder setPosition(one.panda_number.wcs.protos.Vector3 value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
        onChanged();
      } else {
        positionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.webcamshooting.Vector3 position = 1;</code>
     */
    public Builder setPosition(
        one.panda_number.wcs.protos.Vector3.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
        onChanged();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.webcamshooting.Vector3 position = 1;</code>
     */
    public Builder mergePosition(one.panda_number.wcs.protos.Vector3 value) {
      if (positionBuilder_ == null) {
        if (position_ != null) {
          position_ =
            one.panda_number.wcs.protos.Vector3.newBuilder(position_).mergeFrom(value).buildPartial();
        } else {
          position_ = value;
        }
        onChanged();
      } else {
        positionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.webcamshooting.Vector3 position = 1;</code>
     */
    public Builder clearPosition() {
      if (positionBuilder_ == null) {
        position_ = null;
        onChanged();
      } else {
        position_ = null;
        positionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.webcamshooting.Vector3 position = 1;</code>
     */
    public one.panda_number.wcs.protos.Vector3.Builder getPositionBuilder() {
      
      onChanged();
      return getPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.webcamshooting.Vector3 position = 1;</code>
     */
    public one.panda_number.wcs.protos.Vector3OrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            one.panda_number.wcs.protos.Vector3.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.webcamshooting.Vector3 position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.Vector3, one.panda_number.wcs.protos.Vector3.Builder, one.panda_number.wcs.protos.Vector3OrBuilder> 
        getPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            one.panda_number.wcs.protos.Vector3, one.panda_number.wcs.protos.Vector3.Builder, one.panda_number.wcs.protos.Vector3OrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    private one.panda_number.wcs.protos.Vector3 velocity_;
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.Vector3, one.panda_number.wcs.protos.Vector3.Builder, one.panda_number.wcs.protos.Vector3OrBuilder> velocityBuilder_;
    /**
     * <code>.webcamshooting.Vector3 velocity = 2;</code>
     * @return Whether the velocity field is set.
     */
    public boolean hasVelocity() {
      return velocityBuilder_ != null || velocity_ != null;
    }
    /**
     * <code>.webcamshooting.Vector3 velocity = 2;</code>
     * @return The velocity.
     */
    public one.panda_number.wcs.protos.Vector3 getVelocity() {
      if (velocityBuilder_ == null) {
        return velocity_ == null ? one.panda_number.wcs.protos.Vector3.getDefaultInstance() : velocity_;
      } else {
        return velocityBuilder_.getMessage();
      }
    }
    /**
     * <code>.webcamshooting.Vector3 velocity = 2;</code>
     */
    public Builder setVelocity(one.panda_number.wcs.protos.Vector3 value) {
      if (velocityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        velocity_ = value;
        onChanged();
      } else {
        velocityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.webcamshooting.Vector3 velocity = 2;</code>
     */
    public Builder setVelocity(
        one.panda_number.wcs.protos.Vector3.Builder builderForValue) {
      if (velocityBuilder_ == null) {
        velocity_ = builderForValue.build();
        onChanged();
      } else {
        velocityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.webcamshooting.Vector3 velocity = 2;</code>
     */
    public Builder mergeVelocity(one.panda_number.wcs.protos.Vector3 value) {
      if (velocityBuilder_ == null) {
        if (velocity_ != null) {
          velocity_ =
            one.panda_number.wcs.protos.Vector3.newBuilder(velocity_).mergeFrom(value).buildPartial();
        } else {
          velocity_ = value;
        }
        onChanged();
      } else {
        velocityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.webcamshooting.Vector3 velocity = 2;</code>
     */
    public Builder clearVelocity() {
      if (velocityBuilder_ == null) {
        velocity_ = null;
        onChanged();
      } else {
        velocity_ = null;
        velocityBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.webcamshooting.Vector3 velocity = 2;</code>
     */
    public one.panda_number.wcs.protos.Vector3.Builder getVelocityBuilder() {
      
      onChanged();
      return getVelocityFieldBuilder().getBuilder();
    }
    /**
     * <code>.webcamshooting.Vector3 velocity = 2;</code>
     */
    public one.panda_number.wcs.protos.Vector3OrBuilder getVelocityOrBuilder() {
      if (velocityBuilder_ != null) {
        return velocityBuilder_.getMessageOrBuilder();
      } else {
        return velocity_ == null ?
            one.panda_number.wcs.protos.Vector3.getDefaultInstance() : velocity_;
      }
    }
    /**
     * <code>.webcamshooting.Vector3 velocity = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.Vector3, one.panda_number.wcs.protos.Vector3.Builder, one.panda_number.wcs.protos.Vector3OrBuilder> 
        getVelocityFieldBuilder() {
      if (velocityBuilder_ == null) {
        velocityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            one.panda_number.wcs.protos.Vector3, one.panda_number.wcs.protos.Vector3.Builder, one.panda_number.wcs.protos.Vector3OrBuilder>(
                getVelocity(),
                getParentForChildren(),
                isClean());
        velocity_ = null;
      }
      return velocityBuilder_;
    }

    private float yaw_ ;
    /**
     * <code>float yaw = 3;</code>
     * @return The yaw.
     */
    @java.lang.Override
    public float getYaw() {
      return yaw_;
    }
    /**
     * <code>float yaw = 3;</code>
     * @param value The yaw to set.
     * @return This builder for chaining.
     */
    public Builder setYaw(float value) {
      
      yaw_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float yaw = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearYaw() {
      
      yaw_ = 0F;
      onChanged();
      return this;
    }

    private float pitch_ ;
    /**
     * <code>float pitch = 4;</code>
     * @return The pitch.
     */
    @java.lang.Override
    public float getPitch() {
      return pitch_;
    }
    /**
     * <code>float pitch = 4;</code>
     * @param value The pitch to set.
     * @return This builder for chaining.
     */
    public Builder setPitch(float value) {
      
      pitch_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float pitch = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPitch() {
      
      pitch_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:webcamshooting.Player)
  }

  // @@protoc_insertion_point(class_scope:webcamshooting.Player)
  private static final one.panda_number.wcs.protos.Player DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new one.panda_number.wcs.protos.Player();
  }

  public static one.panda_number.wcs.protos.Player getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Player>
      PARSER = new com.google.protobuf.AbstractParser<Player>() {
    @java.lang.Override
    public Player parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Player(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Player> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Player> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public one.panda_number.wcs.protos.Player getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

