// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface PlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.Player)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.webcamshooting.Vector3 position = 1;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.webcamshooting.Vector3 position = 1;</code>
   * @return The position.
   */
  one.panda_number.wcs.protos.Vector3 getPosition();
  /**
   * <code>.webcamshooting.Vector3 position = 1;</code>
   */
  one.panda_number.wcs.protos.Vector3OrBuilder getPositionOrBuilder();

  /**
   * <code>.webcamshooting.Vector3 velocity = 2;</code>
   * @return Whether the velocity field is set.
   */
  boolean hasVelocity();
  /**
   * <code>.webcamshooting.Vector3 velocity = 2;</code>
   * @return The velocity.
   */
  one.panda_number.wcs.protos.Vector3 getVelocity();
  /**
   * <code>.webcamshooting.Vector3 velocity = 2;</code>
   */
  one.panda_number.wcs.protos.Vector3OrBuilder getVelocityOrBuilder();

  /**
   * <code>float yaw = 3;</code>
   * @return The yaw.
   */
  float getYaw();

  /**
   * <code>float pitch = 4;</code>
   * @return The pitch.
   */
  float getPitch();
}
