// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface PlayerUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.PlayerUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pid = 1;</code>
   * @return The pid.
   */
  java.lang.String getPid();
  /**
   * <code>string pid = 1;</code>
   * @return The bytes for pid.
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>.webcamshooting.Player player = 2;</code>
   * @return Whether the player field is set.
   */
  boolean hasPlayer();
  /**
   * <code>.webcamshooting.Player player = 2;</code>
   * @return The player.
   */
  one.panda_number.wcs.protos.Player getPlayer();
  /**
   * <code>.webcamshooting.Player player = 2;</code>
   */
  one.panda_number.wcs.protos.PlayerOrBuilder getPlayerOrBuilder();

  /**
   * <code>bool dead = 3;</code>
   * @return The dead.
   */
  boolean getDead();

  /**
   * <code>bool fired = 6;</code>
   * @return The fired.
   */
  boolean getFired();

  /**
   * <code>repeated .webcamshooting.DamageResponse damages = 7;</code>
   */
  java.util.List<one.panda_number.wcs.protos.DamageResponse> 
      getDamagesList();
  /**
   * <code>repeated .webcamshooting.DamageResponse damages = 7;</code>
   */
  one.panda_number.wcs.protos.DamageResponse getDamages(int index);
  /**
   * <code>repeated .webcamshooting.DamageResponse damages = 7;</code>
   */
  int getDamagesCount();
  /**
   * <code>repeated .webcamshooting.DamageResponse damages = 7;</code>
   */
  java.util.List<? extends one.panda_number.wcs.protos.DamageResponseOrBuilder> 
      getDamagesOrBuilderList();
  /**
   * <code>repeated .webcamshooting.DamageResponse damages = 7;</code>
   */
  one.panda_number.wcs.protos.DamageResponseOrBuilder getDamagesOrBuilder(
      int index);
}
