// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

/**
 * Protobuf type {@code webcamshooting.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:webcamshooting.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            one.panda_number.wcs.protos.JoinRequest.Builder subBuilder = null;
            if (requestOneofCase_ == 1) {
              subBuilder = ((one.panda_number.wcs.protos.JoinRequest) requestOneof_).toBuilder();
            }
            requestOneof_ =
                input.readMessage(one.panda_number.wcs.protos.JoinRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((one.panda_number.wcs.protos.JoinRequest) requestOneof_);
              requestOneof_ = subBuilder.buildPartial();
            }
            requestOneofCase_ = 1;
            break;
          }
          case 18: {
            one.panda_number.wcs.protos.ClientUpdate.Builder subBuilder = null;
            if (requestOneofCase_ == 2) {
              subBuilder = ((one.panda_number.wcs.protos.ClientUpdate) requestOneof_).toBuilder();
            }
            requestOneof_ =
                input.readMessage(one.panda_number.wcs.protos.ClientUpdate.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((one.panda_number.wcs.protos.ClientUpdate) requestOneof_);
              requestOneof_ = subBuilder.buildPartial();
            }
            requestOneofCase_ = 2;
            break;
          }
          case 26: {
            one.panda_number.wcs.protos.DeadUpdate.Builder subBuilder = null;
            if (requestOneofCase_ == 3) {
              subBuilder = ((one.panda_number.wcs.protos.DeadUpdate) requestOneof_).toBuilder();
            }
            requestOneof_ =
                input.readMessage(one.panda_number.wcs.protos.DeadUpdate.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((one.panda_number.wcs.protos.DeadUpdate) requestOneof_);
              requestOneof_ = subBuilder.buildPartial();
            }
            requestOneofCase_ = 3;
            break;
          }
          case 34: {
            one.panda_number.wcs.protos.RespawnRequest.Builder subBuilder = null;
            if (requestOneofCase_ == 4) {
              subBuilder = ((one.panda_number.wcs.protos.RespawnRequest) requestOneof_).toBuilder();
            }
            requestOneof_ =
                input.readMessage(one.panda_number.wcs.protos.RespawnRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((one.panda_number.wcs.protos.RespawnRequest) requestOneof_);
              requestOneof_ = subBuilder.buildPartial();
            }
            requestOneofCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            one.panda_number.wcs.protos.Request.class, one.panda_number.wcs.protos.Request.Builder.class);
  }

  private int requestOneofCase_ = 0;
  private java.lang.Object requestOneof_;
  public enum RequestOneofCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    JOIN_REQUEST(1),
    CLIENT_UPDATE(2),
    DEAD_UPDATE(3),
    RESPAWN_REQUEST(4),
    REQUESTONEOF_NOT_SET(0);
    private final int value;
    private RequestOneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestOneofCase forNumber(int value) {
      switch (value) {
        case 1: return JOIN_REQUEST;
        case 2: return CLIENT_UPDATE;
        case 3: return DEAD_UPDATE;
        case 4: return RESPAWN_REQUEST;
        case 0: return REQUESTONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestOneofCase
  getRequestOneofCase() {
    return RequestOneofCase.forNumber(
        requestOneofCase_);
  }

  public static final int JOIN_REQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.webcamshooting.JoinRequest join_request = 1;</code>
   * @return Whether the joinRequest field is set.
   */
  @java.lang.Override
  public boolean hasJoinRequest() {
    return requestOneofCase_ == 1;
  }
  /**
   * <code>.webcamshooting.JoinRequest join_request = 1;</code>
   * @return The joinRequest.
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.JoinRequest getJoinRequest() {
    if (requestOneofCase_ == 1) {
       return (one.panda_number.wcs.protos.JoinRequest) requestOneof_;
    }
    return one.panda_number.wcs.protos.JoinRequest.getDefaultInstance();
  }
  /**
   * <code>.webcamshooting.JoinRequest join_request = 1;</code>
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.JoinRequestOrBuilder getJoinRequestOrBuilder() {
    if (requestOneofCase_ == 1) {
       return (one.panda_number.wcs.protos.JoinRequest) requestOneof_;
    }
    return one.panda_number.wcs.protos.JoinRequest.getDefaultInstance();
  }

  public static final int CLIENT_UPDATE_FIELD_NUMBER = 2;
  /**
   * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
   * @return Whether the clientUpdate field is set.
   */
  @java.lang.Override
  public boolean hasClientUpdate() {
    return requestOneofCase_ == 2;
  }
  /**
   * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
   * @return The clientUpdate.
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.ClientUpdate getClientUpdate() {
    if (requestOneofCase_ == 2) {
       return (one.panda_number.wcs.protos.ClientUpdate) requestOneof_;
    }
    return one.panda_number.wcs.protos.ClientUpdate.getDefaultInstance();
  }
  /**
   * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.ClientUpdateOrBuilder getClientUpdateOrBuilder() {
    if (requestOneofCase_ == 2) {
       return (one.panda_number.wcs.protos.ClientUpdate) requestOneof_;
    }
    return one.panda_number.wcs.protos.ClientUpdate.getDefaultInstance();
  }

  public static final int DEAD_UPDATE_FIELD_NUMBER = 3;
  /**
   * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
   * @return Whether the deadUpdate field is set.
   */
  @java.lang.Override
  public boolean hasDeadUpdate() {
    return requestOneofCase_ == 3;
  }
  /**
   * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
   * @return The deadUpdate.
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.DeadUpdate getDeadUpdate() {
    if (requestOneofCase_ == 3) {
       return (one.panda_number.wcs.protos.DeadUpdate) requestOneof_;
    }
    return one.panda_number.wcs.protos.DeadUpdate.getDefaultInstance();
  }
  /**
   * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.DeadUpdateOrBuilder getDeadUpdateOrBuilder() {
    if (requestOneofCase_ == 3) {
       return (one.panda_number.wcs.protos.DeadUpdate) requestOneof_;
    }
    return one.panda_number.wcs.protos.DeadUpdate.getDefaultInstance();
  }

  public static final int RESPAWN_REQUEST_FIELD_NUMBER = 4;
  /**
   * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
   * @return Whether the respawnRequest field is set.
   */
  @java.lang.Override
  public boolean hasRespawnRequest() {
    return requestOneofCase_ == 4;
  }
  /**
   * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
   * @return The respawnRequest.
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.RespawnRequest getRespawnRequest() {
    if (requestOneofCase_ == 4) {
       return (one.panda_number.wcs.protos.RespawnRequest) requestOneof_;
    }
    return one.panda_number.wcs.protos.RespawnRequest.getDefaultInstance();
  }
  /**
   * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.RespawnRequestOrBuilder getRespawnRequestOrBuilder() {
    if (requestOneofCase_ == 4) {
       return (one.panda_number.wcs.protos.RespawnRequest) requestOneof_;
    }
    return one.panda_number.wcs.protos.RespawnRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestOneofCase_ == 1) {
      output.writeMessage(1, (one.panda_number.wcs.protos.JoinRequest) requestOneof_);
    }
    if (requestOneofCase_ == 2) {
      output.writeMessage(2, (one.panda_number.wcs.protos.ClientUpdate) requestOneof_);
    }
    if (requestOneofCase_ == 3) {
      output.writeMessage(3, (one.panda_number.wcs.protos.DeadUpdate) requestOneof_);
    }
    if (requestOneofCase_ == 4) {
      output.writeMessage(4, (one.panda_number.wcs.protos.RespawnRequest) requestOneof_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestOneofCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (one.panda_number.wcs.protos.JoinRequest) requestOneof_);
    }
    if (requestOneofCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (one.panda_number.wcs.protos.ClientUpdate) requestOneof_);
    }
    if (requestOneofCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (one.panda_number.wcs.protos.DeadUpdate) requestOneof_);
    }
    if (requestOneofCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (one.panda_number.wcs.protos.RespawnRequest) requestOneof_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof one.panda_number.wcs.protos.Request)) {
      return super.equals(obj);
    }
    one.panda_number.wcs.protos.Request other = (one.panda_number.wcs.protos.Request) obj;

    if (!getRequestOneofCase().equals(other.getRequestOneofCase())) return false;
    switch (requestOneofCase_) {
      case 1:
        if (!getJoinRequest()
            .equals(other.getJoinRequest())) return false;
        break;
      case 2:
        if (!getClientUpdate()
            .equals(other.getClientUpdate())) return false;
        break;
      case 3:
        if (!getDeadUpdate()
            .equals(other.getDeadUpdate())) return false;
        break;
      case 4:
        if (!getRespawnRequest()
            .equals(other.getRespawnRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestOneofCase_) {
      case 1:
        hash = (37 * hash) + JOIN_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getJoinRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CLIENT_UPDATE_FIELD_NUMBER;
        hash = (53 * hash) + getClientUpdate().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DEAD_UPDATE_FIELD_NUMBER;
        hash = (53 * hash) + getDeadUpdate().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RESPAWN_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRespawnRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static one.panda_number.wcs.protos.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static one.panda_number.wcs.protos.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static one.panda_number.wcs.protos.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static one.panda_number.wcs.protos.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static one.panda_number.wcs.protos.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static one.panda_number.wcs.protos.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static one.panda_number.wcs.protos.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(one.panda_number.wcs.protos.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code webcamshooting.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:webcamshooting.Request)
      one.panda_number.wcs.protos.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              one.panda_number.wcs.protos.Request.class, one.panda_number.wcs.protos.Request.Builder.class);
    }

    // Construct using one.panda_number.wcs.protos.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestOneofCase_ = 0;
      requestOneof_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Request_descriptor;
    }

    @java.lang.Override
    public one.panda_number.wcs.protos.Request getDefaultInstanceForType() {
      return one.panda_number.wcs.protos.Request.getDefaultInstance();
    }

    @java.lang.Override
    public one.panda_number.wcs.protos.Request build() {
      one.panda_number.wcs.protos.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public one.panda_number.wcs.protos.Request buildPartial() {
      one.panda_number.wcs.protos.Request result = new one.panda_number.wcs.protos.Request(this);
      if (requestOneofCase_ == 1) {
        if (joinRequestBuilder_ == null) {
          result.requestOneof_ = requestOneof_;
        } else {
          result.requestOneof_ = joinRequestBuilder_.build();
        }
      }
      if (requestOneofCase_ == 2) {
        if (clientUpdateBuilder_ == null) {
          result.requestOneof_ = requestOneof_;
        } else {
          result.requestOneof_ = clientUpdateBuilder_.build();
        }
      }
      if (requestOneofCase_ == 3) {
        if (deadUpdateBuilder_ == null) {
          result.requestOneof_ = requestOneof_;
        } else {
          result.requestOneof_ = deadUpdateBuilder_.build();
        }
      }
      if (requestOneofCase_ == 4) {
        if (respawnRequestBuilder_ == null) {
          result.requestOneof_ = requestOneof_;
        } else {
          result.requestOneof_ = respawnRequestBuilder_.build();
        }
      }
      result.requestOneofCase_ = requestOneofCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof one.panda_number.wcs.protos.Request) {
        return mergeFrom((one.panda_number.wcs.protos.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(one.panda_number.wcs.protos.Request other) {
      if (other == one.panda_number.wcs.protos.Request.getDefaultInstance()) return this;
      switch (other.getRequestOneofCase()) {
        case JOIN_REQUEST: {
          mergeJoinRequest(other.getJoinRequest());
          break;
        }
        case CLIENT_UPDATE: {
          mergeClientUpdate(other.getClientUpdate());
          break;
        }
        case DEAD_UPDATE: {
          mergeDeadUpdate(other.getDeadUpdate());
          break;
        }
        case RESPAWN_REQUEST: {
          mergeRespawnRequest(other.getRespawnRequest());
          break;
        }
        case REQUESTONEOF_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      one.panda_number.wcs.protos.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (one.panda_number.wcs.protos.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int requestOneofCase_ = 0;
    private java.lang.Object requestOneof_;
    public RequestOneofCase
        getRequestOneofCase() {
      return RequestOneofCase.forNumber(
          requestOneofCase_);
    }

    public Builder clearRequestOneof() {
      requestOneofCase_ = 0;
      requestOneof_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.JoinRequest, one.panda_number.wcs.protos.JoinRequest.Builder, one.panda_number.wcs.protos.JoinRequestOrBuilder> joinRequestBuilder_;
    /**
     * <code>.webcamshooting.JoinRequest join_request = 1;</code>
     * @return Whether the joinRequest field is set.
     */
    @java.lang.Override
    public boolean hasJoinRequest() {
      return requestOneofCase_ == 1;
    }
    /**
     * <code>.webcamshooting.JoinRequest join_request = 1;</code>
     * @return The joinRequest.
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.JoinRequest getJoinRequest() {
      if (joinRequestBuilder_ == null) {
        if (requestOneofCase_ == 1) {
          return (one.panda_number.wcs.protos.JoinRequest) requestOneof_;
        }
        return one.panda_number.wcs.protos.JoinRequest.getDefaultInstance();
      } else {
        if (requestOneofCase_ == 1) {
          return joinRequestBuilder_.getMessage();
        }
        return one.panda_number.wcs.protos.JoinRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.JoinRequest join_request = 1;</code>
     */
    public Builder setJoinRequest(one.panda_number.wcs.protos.JoinRequest value) {
      if (joinRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestOneof_ = value;
        onChanged();
      } else {
        joinRequestBuilder_.setMessage(value);
      }
      requestOneofCase_ = 1;
      return this;
    }
    /**
     * <code>.webcamshooting.JoinRequest join_request = 1;</code>
     */
    public Builder setJoinRequest(
        one.panda_number.wcs.protos.JoinRequest.Builder builderForValue) {
      if (joinRequestBuilder_ == null) {
        requestOneof_ = builderForValue.build();
        onChanged();
      } else {
        joinRequestBuilder_.setMessage(builderForValue.build());
      }
      requestOneofCase_ = 1;
      return this;
    }
    /**
     * <code>.webcamshooting.JoinRequest join_request = 1;</code>
     */
    public Builder mergeJoinRequest(one.panda_number.wcs.protos.JoinRequest value) {
      if (joinRequestBuilder_ == null) {
        if (requestOneofCase_ == 1 &&
            requestOneof_ != one.panda_number.wcs.protos.JoinRequest.getDefaultInstance()) {
          requestOneof_ = one.panda_number.wcs.protos.JoinRequest.newBuilder((one.panda_number.wcs.protos.JoinRequest) requestOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          requestOneof_ = value;
        }
        onChanged();
      } else {
        if (requestOneofCase_ == 1) {
          joinRequestBuilder_.mergeFrom(value);
        } else {
          joinRequestBuilder_.setMessage(value);
        }
      }
      requestOneofCase_ = 1;
      return this;
    }
    /**
     * <code>.webcamshooting.JoinRequest join_request = 1;</code>
     */
    public Builder clearJoinRequest() {
      if (joinRequestBuilder_ == null) {
        if (requestOneofCase_ == 1) {
          requestOneofCase_ = 0;
          requestOneof_ = null;
          onChanged();
        }
      } else {
        if (requestOneofCase_ == 1) {
          requestOneofCase_ = 0;
          requestOneof_ = null;
        }
        joinRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.webcamshooting.JoinRequest join_request = 1;</code>
     */
    public one.panda_number.wcs.protos.JoinRequest.Builder getJoinRequestBuilder() {
      return getJoinRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.webcamshooting.JoinRequest join_request = 1;</code>
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.JoinRequestOrBuilder getJoinRequestOrBuilder() {
      if ((requestOneofCase_ == 1) && (joinRequestBuilder_ != null)) {
        return joinRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestOneofCase_ == 1) {
          return (one.panda_number.wcs.protos.JoinRequest) requestOneof_;
        }
        return one.panda_number.wcs.protos.JoinRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.JoinRequest join_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.JoinRequest, one.panda_number.wcs.protos.JoinRequest.Builder, one.panda_number.wcs.protos.JoinRequestOrBuilder> 
        getJoinRequestFieldBuilder() {
      if (joinRequestBuilder_ == null) {
        if (!(requestOneofCase_ == 1)) {
          requestOneof_ = one.panda_number.wcs.protos.JoinRequest.getDefaultInstance();
        }
        joinRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            one.panda_number.wcs.protos.JoinRequest, one.panda_number.wcs.protos.JoinRequest.Builder, one.panda_number.wcs.protos.JoinRequestOrBuilder>(
                (one.panda_number.wcs.protos.JoinRequest) requestOneof_,
                getParentForChildren(),
                isClean());
        requestOneof_ = null;
      }
      requestOneofCase_ = 1;
      onChanged();;
      return joinRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.ClientUpdate, one.panda_number.wcs.protos.ClientUpdate.Builder, one.panda_number.wcs.protos.ClientUpdateOrBuilder> clientUpdateBuilder_;
    /**
     * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
     * @return Whether the clientUpdate field is set.
     */
    @java.lang.Override
    public boolean hasClientUpdate() {
      return requestOneofCase_ == 2;
    }
    /**
     * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
     * @return The clientUpdate.
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.ClientUpdate getClientUpdate() {
      if (clientUpdateBuilder_ == null) {
        if (requestOneofCase_ == 2) {
          return (one.panda_number.wcs.protos.ClientUpdate) requestOneof_;
        }
        return one.panda_number.wcs.protos.ClientUpdate.getDefaultInstance();
      } else {
        if (requestOneofCase_ == 2) {
          return clientUpdateBuilder_.getMessage();
        }
        return one.panda_number.wcs.protos.ClientUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
     */
    public Builder setClientUpdate(one.panda_number.wcs.protos.ClientUpdate value) {
      if (clientUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestOneof_ = value;
        onChanged();
      } else {
        clientUpdateBuilder_.setMessage(value);
      }
      requestOneofCase_ = 2;
      return this;
    }
    /**
     * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
     */
    public Builder setClientUpdate(
        one.panda_number.wcs.protos.ClientUpdate.Builder builderForValue) {
      if (clientUpdateBuilder_ == null) {
        requestOneof_ = builderForValue.build();
        onChanged();
      } else {
        clientUpdateBuilder_.setMessage(builderForValue.build());
      }
      requestOneofCase_ = 2;
      return this;
    }
    /**
     * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
     */
    public Builder mergeClientUpdate(one.panda_number.wcs.protos.ClientUpdate value) {
      if (clientUpdateBuilder_ == null) {
        if (requestOneofCase_ == 2 &&
            requestOneof_ != one.panda_number.wcs.protos.ClientUpdate.getDefaultInstance()) {
          requestOneof_ = one.panda_number.wcs.protos.ClientUpdate.newBuilder((one.panda_number.wcs.protos.ClientUpdate) requestOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          requestOneof_ = value;
        }
        onChanged();
      } else {
        if (requestOneofCase_ == 2) {
          clientUpdateBuilder_.mergeFrom(value);
        } else {
          clientUpdateBuilder_.setMessage(value);
        }
      }
      requestOneofCase_ = 2;
      return this;
    }
    /**
     * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
     */
    public Builder clearClientUpdate() {
      if (clientUpdateBuilder_ == null) {
        if (requestOneofCase_ == 2) {
          requestOneofCase_ = 0;
          requestOneof_ = null;
          onChanged();
        }
      } else {
        if (requestOneofCase_ == 2) {
          requestOneofCase_ = 0;
          requestOneof_ = null;
        }
        clientUpdateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
     */
    public one.panda_number.wcs.protos.ClientUpdate.Builder getClientUpdateBuilder() {
      return getClientUpdateFieldBuilder().getBuilder();
    }
    /**
     * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.ClientUpdateOrBuilder getClientUpdateOrBuilder() {
      if ((requestOneofCase_ == 2) && (clientUpdateBuilder_ != null)) {
        return clientUpdateBuilder_.getMessageOrBuilder();
      } else {
        if (requestOneofCase_ == 2) {
          return (one.panda_number.wcs.protos.ClientUpdate) requestOneof_;
        }
        return one.panda_number.wcs.protos.ClientUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.ClientUpdate client_update = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.ClientUpdate, one.panda_number.wcs.protos.ClientUpdate.Builder, one.panda_number.wcs.protos.ClientUpdateOrBuilder> 
        getClientUpdateFieldBuilder() {
      if (clientUpdateBuilder_ == null) {
        if (!(requestOneofCase_ == 2)) {
          requestOneof_ = one.panda_number.wcs.protos.ClientUpdate.getDefaultInstance();
        }
        clientUpdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            one.panda_number.wcs.protos.ClientUpdate, one.panda_number.wcs.protos.ClientUpdate.Builder, one.panda_number.wcs.protos.ClientUpdateOrBuilder>(
                (one.panda_number.wcs.protos.ClientUpdate) requestOneof_,
                getParentForChildren(),
                isClean());
        requestOneof_ = null;
      }
      requestOneofCase_ = 2;
      onChanged();;
      return clientUpdateBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.DeadUpdate, one.panda_number.wcs.protos.DeadUpdate.Builder, one.panda_number.wcs.protos.DeadUpdateOrBuilder> deadUpdateBuilder_;
    /**
     * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
     * @return Whether the deadUpdate field is set.
     */
    @java.lang.Override
    public boolean hasDeadUpdate() {
      return requestOneofCase_ == 3;
    }
    /**
     * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
     * @return The deadUpdate.
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.DeadUpdate getDeadUpdate() {
      if (deadUpdateBuilder_ == null) {
        if (requestOneofCase_ == 3) {
          return (one.panda_number.wcs.protos.DeadUpdate) requestOneof_;
        }
        return one.panda_number.wcs.protos.DeadUpdate.getDefaultInstance();
      } else {
        if (requestOneofCase_ == 3) {
          return deadUpdateBuilder_.getMessage();
        }
        return one.panda_number.wcs.protos.DeadUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
     */
    public Builder setDeadUpdate(one.panda_number.wcs.protos.DeadUpdate value) {
      if (deadUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestOneof_ = value;
        onChanged();
      } else {
        deadUpdateBuilder_.setMessage(value);
      }
      requestOneofCase_ = 3;
      return this;
    }
    /**
     * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
     */
    public Builder setDeadUpdate(
        one.panda_number.wcs.protos.DeadUpdate.Builder builderForValue) {
      if (deadUpdateBuilder_ == null) {
        requestOneof_ = builderForValue.build();
        onChanged();
      } else {
        deadUpdateBuilder_.setMessage(builderForValue.build());
      }
      requestOneofCase_ = 3;
      return this;
    }
    /**
     * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
     */
    public Builder mergeDeadUpdate(one.panda_number.wcs.protos.DeadUpdate value) {
      if (deadUpdateBuilder_ == null) {
        if (requestOneofCase_ == 3 &&
            requestOneof_ != one.panda_number.wcs.protos.DeadUpdate.getDefaultInstance()) {
          requestOneof_ = one.panda_number.wcs.protos.DeadUpdate.newBuilder((one.panda_number.wcs.protos.DeadUpdate) requestOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          requestOneof_ = value;
        }
        onChanged();
      } else {
        if (requestOneofCase_ == 3) {
          deadUpdateBuilder_.mergeFrom(value);
        } else {
          deadUpdateBuilder_.setMessage(value);
        }
      }
      requestOneofCase_ = 3;
      return this;
    }
    /**
     * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
     */
    public Builder clearDeadUpdate() {
      if (deadUpdateBuilder_ == null) {
        if (requestOneofCase_ == 3) {
          requestOneofCase_ = 0;
          requestOneof_ = null;
          onChanged();
        }
      } else {
        if (requestOneofCase_ == 3) {
          requestOneofCase_ = 0;
          requestOneof_ = null;
        }
        deadUpdateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
     */
    public one.panda_number.wcs.protos.DeadUpdate.Builder getDeadUpdateBuilder() {
      return getDeadUpdateFieldBuilder().getBuilder();
    }
    /**
     * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.DeadUpdateOrBuilder getDeadUpdateOrBuilder() {
      if ((requestOneofCase_ == 3) && (deadUpdateBuilder_ != null)) {
        return deadUpdateBuilder_.getMessageOrBuilder();
      } else {
        if (requestOneofCase_ == 3) {
          return (one.panda_number.wcs.protos.DeadUpdate) requestOneof_;
        }
        return one.panda_number.wcs.protos.DeadUpdate.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.DeadUpdate dead_update = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.DeadUpdate, one.panda_number.wcs.protos.DeadUpdate.Builder, one.panda_number.wcs.protos.DeadUpdateOrBuilder> 
        getDeadUpdateFieldBuilder() {
      if (deadUpdateBuilder_ == null) {
        if (!(requestOneofCase_ == 3)) {
          requestOneof_ = one.panda_number.wcs.protos.DeadUpdate.getDefaultInstance();
        }
        deadUpdateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            one.panda_number.wcs.protos.DeadUpdate, one.panda_number.wcs.protos.DeadUpdate.Builder, one.panda_number.wcs.protos.DeadUpdateOrBuilder>(
                (one.panda_number.wcs.protos.DeadUpdate) requestOneof_,
                getParentForChildren(),
                isClean());
        requestOneof_ = null;
      }
      requestOneofCase_ = 3;
      onChanged();;
      return deadUpdateBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.RespawnRequest, one.panda_number.wcs.protos.RespawnRequest.Builder, one.panda_number.wcs.protos.RespawnRequestOrBuilder> respawnRequestBuilder_;
    /**
     * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
     * @return Whether the respawnRequest field is set.
     */
    @java.lang.Override
    public boolean hasRespawnRequest() {
      return requestOneofCase_ == 4;
    }
    /**
     * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
     * @return The respawnRequest.
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.RespawnRequest getRespawnRequest() {
      if (respawnRequestBuilder_ == null) {
        if (requestOneofCase_ == 4) {
          return (one.panda_number.wcs.protos.RespawnRequest) requestOneof_;
        }
        return one.panda_number.wcs.protos.RespawnRequest.getDefaultInstance();
      } else {
        if (requestOneofCase_ == 4) {
          return respawnRequestBuilder_.getMessage();
        }
        return one.panda_number.wcs.protos.RespawnRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
     */
    public Builder setRespawnRequest(one.panda_number.wcs.protos.RespawnRequest value) {
      if (respawnRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestOneof_ = value;
        onChanged();
      } else {
        respawnRequestBuilder_.setMessage(value);
      }
      requestOneofCase_ = 4;
      return this;
    }
    /**
     * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
     */
    public Builder setRespawnRequest(
        one.panda_number.wcs.protos.RespawnRequest.Builder builderForValue) {
      if (respawnRequestBuilder_ == null) {
        requestOneof_ = builderForValue.build();
        onChanged();
      } else {
        respawnRequestBuilder_.setMessage(builderForValue.build());
      }
      requestOneofCase_ = 4;
      return this;
    }
    /**
     * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
     */
    public Builder mergeRespawnRequest(one.panda_number.wcs.protos.RespawnRequest value) {
      if (respawnRequestBuilder_ == null) {
        if (requestOneofCase_ == 4 &&
            requestOneof_ != one.panda_number.wcs.protos.RespawnRequest.getDefaultInstance()) {
          requestOneof_ = one.panda_number.wcs.protos.RespawnRequest.newBuilder((one.panda_number.wcs.protos.RespawnRequest) requestOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          requestOneof_ = value;
        }
        onChanged();
      } else {
        if (requestOneofCase_ == 4) {
          respawnRequestBuilder_.mergeFrom(value);
        } else {
          respawnRequestBuilder_.setMessage(value);
        }
      }
      requestOneofCase_ = 4;
      return this;
    }
    /**
     * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
     */
    public Builder clearRespawnRequest() {
      if (respawnRequestBuilder_ == null) {
        if (requestOneofCase_ == 4) {
          requestOneofCase_ = 0;
          requestOneof_ = null;
          onChanged();
        }
      } else {
        if (requestOneofCase_ == 4) {
          requestOneofCase_ = 0;
          requestOneof_ = null;
        }
        respawnRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
     */
    public one.panda_number.wcs.protos.RespawnRequest.Builder getRespawnRequestBuilder() {
      return getRespawnRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.RespawnRequestOrBuilder getRespawnRequestOrBuilder() {
      if ((requestOneofCase_ == 4) && (respawnRequestBuilder_ != null)) {
        return respawnRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestOneofCase_ == 4) {
          return (one.panda_number.wcs.protos.RespawnRequest) requestOneof_;
        }
        return one.panda_number.wcs.protos.RespawnRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.RespawnRequest respawn_request = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.RespawnRequest, one.panda_number.wcs.protos.RespawnRequest.Builder, one.panda_number.wcs.protos.RespawnRequestOrBuilder> 
        getRespawnRequestFieldBuilder() {
      if (respawnRequestBuilder_ == null) {
        if (!(requestOneofCase_ == 4)) {
          requestOneof_ = one.panda_number.wcs.protos.RespawnRequest.getDefaultInstance();
        }
        respawnRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            one.panda_number.wcs.protos.RespawnRequest, one.panda_number.wcs.protos.RespawnRequest.Builder, one.panda_number.wcs.protos.RespawnRequestOrBuilder>(
                (one.panda_number.wcs.protos.RespawnRequest) requestOneof_,
                getParentForChildren(),
                isClean());
        requestOneof_ = null;
      }
      requestOneofCase_ = 4;
      onChanged();;
      return respawnRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:webcamshooting.Request)
  }

  // @@protoc_insertion_point(class_scope:webcamshooting.Request)
  private static final one.panda_number.wcs.protos.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new one.panda_number.wcs.protos.Request();
  }

  public static one.panda_number.wcs.protos.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public one.panda_number.wcs.protos.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

