// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

/**
 * Protobuf type {@code webcamshooting.Response}
 */
public final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:webcamshooting.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Response();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            one.panda_number.wcs.protos.PidResponse.Builder subBuilder = null;
            if (responseOneofCase_ == 1) {
              subBuilder = ((one.panda_number.wcs.protos.PidResponse) responseOneof_).toBuilder();
            }
            responseOneof_ =
                input.readMessage(one.panda_number.wcs.protos.PidResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((one.panda_number.wcs.protos.PidResponse) responseOneof_);
              responseOneof_ = subBuilder.buildPartial();
            }
            responseOneofCase_ = 1;
            break;
          }
          case 18: {
            one.panda_number.wcs.protos.UpdateResponse.Builder subBuilder = null;
            if (responseOneofCase_ == 2) {
              subBuilder = ((one.panda_number.wcs.protos.UpdateResponse) responseOneof_).toBuilder();
            }
            responseOneof_ =
                input.readMessage(one.panda_number.wcs.protos.UpdateResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((one.panda_number.wcs.protos.UpdateResponse) responseOneof_);
              responseOneof_ = subBuilder.buildPartial();
            }
            responseOneofCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            one.panda_number.wcs.protos.Response.class, one.panda_number.wcs.protos.Response.Builder.class);
  }

  private int responseOneofCase_ = 0;
  private java.lang.Object responseOneof_;
  public enum ResponseOneofCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PID_RESPONSE(1),
    UPDATE_RESPONSE(2),
    RESPONSEONEOF_NOT_SET(0);
    private final int value;
    private ResponseOneofCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseOneofCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseOneofCase forNumber(int value) {
      switch (value) {
        case 1: return PID_RESPONSE;
        case 2: return UPDATE_RESPONSE;
        case 0: return RESPONSEONEOF_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseOneofCase
  getResponseOneofCase() {
    return ResponseOneofCase.forNumber(
        responseOneofCase_);
  }

  public static final int PID_RESPONSE_FIELD_NUMBER = 1;
  /**
   * <code>.webcamshooting.PidResponse pid_response = 1;</code>
   * @return Whether the pidResponse field is set.
   */
  @java.lang.Override
  public boolean hasPidResponse() {
    return responseOneofCase_ == 1;
  }
  /**
   * <code>.webcamshooting.PidResponse pid_response = 1;</code>
   * @return The pidResponse.
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.PidResponse getPidResponse() {
    if (responseOneofCase_ == 1) {
       return (one.panda_number.wcs.protos.PidResponse) responseOneof_;
    }
    return one.panda_number.wcs.protos.PidResponse.getDefaultInstance();
  }
  /**
   * <code>.webcamshooting.PidResponse pid_response = 1;</code>
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.PidResponseOrBuilder getPidResponseOrBuilder() {
    if (responseOneofCase_ == 1) {
       return (one.panda_number.wcs.protos.PidResponse) responseOneof_;
    }
    return one.panda_number.wcs.protos.PidResponse.getDefaultInstance();
  }

  public static final int UPDATE_RESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
   * @return Whether the updateResponse field is set.
   */
  @java.lang.Override
  public boolean hasUpdateResponse() {
    return responseOneofCase_ == 2;
  }
  /**
   * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
   * @return The updateResponse.
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.UpdateResponse getUpdateResponse() {
    if (responseOneofCase_ == 2) {
       return (one.panda_number.wcs.protos.UpdateResponse) responseOneof_;
    }
    return one.panda_number.wcs.protos.UpdateResponse.getDefaultInstance();
  }
  /**
   * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
   */
  @java.lang.Override
  public one.panda_number.wcs.protos.UpdateResponseOrBuilder getUpdateResponseOrBuilder() {
    if (responseOneofCase_ == 2) {
       return (one.panda_number.wcs.protos.UpdateResponse) responseOneof_;
    }
    return one.panda_number.wcs.protos.UpdateResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseOneofCase_ == 1) {
      output.writeMessage(1, (one.panda_number.wcs.protos.PidResponse) responseOneof_);
    }
    if (responseOneofCase_ == 2) {
      output.writeMessage(2, (one.panda_number.wcs.protos.UpdateResponse) responseOneof_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseOneofCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (one.panda_number.wcs.protos.PidResponse) responseOneof_);
    }
    if (responseOneofCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (one.panda_number.wcs.protos.UpdateResponse) responseOneof_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof one.panda_number.wcs.protos.Response)) {
      return super.equals(obj);
    }
    one.panda_number.wcs.protos.Response other = (one.panda_number.wcs.protos.Response) obj;

    if (!getResponseOneofCase().equals(other.getResponseOneofCase())) return false;
    switch (responseOneofCase_) {
      case 1:
        if (!getPidResponse()
            .equals(other.getPidResponse())) return false;
        break;
      case 2:
        if (!getUpdateResponse()
            .equals(other.getUpdateResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseOneofCase_) {
      case 1:
        hash = (37 * hash) + PID_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getPidResponse().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UPDATE_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static one.panda_number.wcs.protos.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static one.panda_number.wcs.protos.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static one.panda_number.wcs.protos.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static one.panda_number.wcs.protos.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static one.panda_number.wcs.protos.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static one.panda_number.wcs.protos.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static one.panda_number.wcs.protos.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static one.panda_number.wcs.protos.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(one.panda_number.wcs.protos.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code webcamshooting.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:webcamshooting.Response)
      one.panda_number.wcs.protos.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              one.panda_number.wcs.protos.Response.class, one.panda_number.wcs.protos.Response.Builder.class);
    }

    // Construct using one.panda_number.wcs.protos.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      responseOneofCase_ = 0;
      responseOneof_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return one.panda_number.wcs.protos.GameProtos.internal_static_webcamshooting_Response_descriptor;
    }

    @java.lang.Override
    public one.panda_number.wcs.protos.Response getDefaultInstanceForType() {
      return one.panda_number.wcs.protos.Response.getDefaultInstance();
    }

    @java.lang.Override
    public one.panda_number.wcs.protos.Response build() {
      one.panda_number.wcs.protos.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public one.panda_number.wcs.protos.Response buildPartial() {
      one.panda_number.wcs.protos.Response result = new one.panda_number.wcs.protos.Response(this);
      if (responseOneofCase_ == 1) {
        if (pidResponseBuilder_ == null) {
          result.responseOneof_ = responseOneof_;
        } else {
          result.responseOneof_ = pidResponseBuilder_.build();
        }
      }
      if (responseOneofCase_ == 2) {
        if (updateResponseBuilder_ == null) {
          result.responseOneof_ = responseOneof_;
        } else {
          result.responseOneof_ = updateResponseBuilder_.build();
        }
      }
      result.responseOneofCase_ = responseOneofCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof one.panda_number.wcs.protos.Response) {
        return mergeFrom((one.panda_number.wcs.protos.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(one.panda_number.wcs.protos.Response other) {
      if (other == one.panda_number.wcs.protos.Response.getDefaultInstance()) return this;
      switch (other.getResponseOneofCase()) {
        case PID_RESPONSE: {
          mergePidResponse(other.getPidResponse());
          break;
        }
        case UPDATE_RESPONSE: {
          mergeUpdateResponse(other.getUpdateResponse());
          break;
        }
        case RESPONSEONEOF_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      one.panda_number.wcs.protos.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (one.panda_number.wcs.protos.Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int responseOneofCase_ = 0;
    private java.lang.Object responseOneof_;
    public ResponseOneofCase
        getResponseOneofCase() {
      return ResponseOneofCase.forNumber(
          responseOneofCase_);
    }

    public Builder clearResponseOneof() {
      responseOneofCase_ = 0;
      responseOneof_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.PidResponse, one.panda_number.wcs.protos.PidResponse.Builder, one.panda_number.wcs.protos.PidResponseOrBuilder> pidResponseBuilder_;
    /**
     * <code>.webcamshooting.PidResponse pid_response = 1;</code>
     * @return Whether the pidResponse field is set.
     */
    @java.lang.Override
    public boolean hasPidResponse() {
      return responseOneofCase_ == 1;
    }
    /**
     * <code>.webcamshooting.PidResponse pid_response = 1;</code>
     * @return The pidResponse.
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.PidResponse getPidResponse() {
      if (pidResponseBuilder_ == null) {
        if (responseOneofCase_ == 1) {
          return (one.panda_number.wcs.protos.PidResponse) responseOneof_;
        }
        return one.panda_number.wcs.protos.PidResponse.getDefaultInstance();
      } else {
        if (responseOneofCase_ == 1) {
          return pidResponseBuilder_.getMessage();
        }
        return one.panda_number.wcs.protos.PidResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.PidResponse pid_response = 1;</code>
     */
    public Builder setPidResponse(one.panda_number.wcs.protos.PidResponse value) {
      if (pidResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responseOneof_ = value;
        onChanged();
      } else {
        pidResponseBuilder_.setMessage(value);
      }
      responseOneofCase_ = 1;
      return this;
    }
    /**
     * <code>.webcamshooting.PidResponse pid_response = 1;</code>
     */
    public Builder setPidResponse(
        one.panda_number.wcs.protos.PidResponse.Builder builderForValue) {
      if (pidResponseBuilder_ == null) {
        responseOneof_ = builderForValue.build();
        onChanged();
      } else {
        pidResponseBuilder_.setMessage(builderForValue.build());
      }
      responseOneofCase_ = 1;
      return this;
    }
    /**
     * <code>.webcamshooting.PidResponse pid_response = 1;</code>
     */
    public Builder mergePidResponse(one.panda_number.wcs.protos.PidResponse value) {
      if (pidResponseBuilder_ == null) {
        if (responseOneofCase_ == 1 &&
            responseOneof_ != one.panda_number.wcs.protos.PidResponse.getDefaultInstance()) {
          responseOneof_ = one.panda_number.wcs.protos.PidResponse.newBuilder((one.panda_number.wcs.protos.PidResponse) responseOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          responseOneof_ = value;
        }
        onChanged();
      } else {
        if (responseOneofCase_ == 1) {
          pidResponseBuilder_.mergeFrom(value);
        } else {
          pidResponseBuilder_.setMessage(value);
        }
      }
      responseOneofCase_ = 1;
      return this;
    }
    /**
     * <code>.webcamshooting.PidResponse pid_response = 1;</code>
     */
    public Builder clearPidResponse() {
      if (pidResponseBuilder_ == null) {
        if (responseOneofCase_ == 1) {
          responseOneofCase_ = 0;
          responseOneof_ = null;
          onChanged();
        }
      } else {
        if (responseOneofCase_ == 1) {
          responseOneofCase_ = 0;
          responseOneof_ = null;
        }
        pidResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.webcamshooting.PidResponse pid_response = 1;</code>
     */
    public one.panda_number.wcs.protos.PidResponse.Builder getPidResponseBuilder() {
      return getPidResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.webcamshooting.PidResponse pid_response = 1;</code>
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.PidResponseOrBuilder getPidResponseOrBuilder() {
      if ((responseOneofCase_ == 1) && (pidResponseBuilder_ != null)) {
        return pidResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseOneofCase_ == 1) {
          return (one.panda_number.wcs.protos.PidResponse) responseOneof_;
        }
        return one.panda_number.wcs.protos.PidResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.PidResponse pid_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.PidResponse, one.panda_number.wcs.protos.PidResponse.Builder, one.panda_number.wcs.protos.PidResponseOrBuilder> 
        getPidResponseFieldBuilder() {
      if (pidResponseBuilder_ == null) {
        if (!(responseOneofCase_ == 1)) {
          responseOneof_ = one.panda_number.wcs.protos.PidResponse.getDefaultInstance();
        }
        pidResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            one.panda_number.wcs.protos.PidResponse, one.panda_number.wcs.protos.PidResponse.Builder, one.panda_number.wcs.protos.PidResponseOrBuilder>(
                (one.panda_number.wcs.protos.PidResponse) responseOneof_,
                getParentForChildren(),
                isClean());
        responseOneof_ = null;
      }
      responseOneofCase_ = 1;
      onChanged();;
      return pidResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.UpdateResponse, one.panda_number.wcs.protos.UpdateResponse.Builder, one.panda_number.wcs.protos.UpdateResponseOrBuilder> updateResponseBuilder_;
    /**
     * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
     * @return Whether the updateResponse field is set.
     */
    @java.lang.Override
    public boolean hasUpdateResponse() {
      return responseOneofCase_ == 2;
    }
    /**
     * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
     * @return The updateResponse.
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.UpdateResponse getUpdateResponse() {
      if (updateResponseBuilder_ == null) {
        if (responseOneofCase_ == 2) {
          return (one.panda_number.wcs.protos.UpdateResponse) responseOneof_;
        }
        return one.panda_number.wcs.protos.UpdateResponse.getDefaultInstance();
      } else {
        if (responseOneofCase_ == 2) {
          return updateResponseBuilder_.getMessage();
        }
        return one.panda_number.wcs.protos.UpdateResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
     */
    public Builder setUpdateResponse(one.panda_number.wcs.protos.UpdateResponse value) {
      if (updateResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responseOneof_ = value;
        onChanged();
      } else {
        updateResponseBuilder_.setMessage(value);
      }
      responseOneofCase_ = 2;
      return this;
    }
    /**
     * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
     */
    public Builder setUpdateResponse(
        one.panda_number.wcs.protos.UpdateResponse.Builder builderForValue) {
      if (updateResponseBuilder_ == null) {
        responseOneof_ = builderForValue.build();
        onChanged();
      } else {
        updateResponseBuilder_.setMessage(builderForValue.build());
      }
      responseOneofCase_ = 2;
      return this;
    }
    /**
     * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
     */
    public Builder mergeUpdateResponse(one.panda_number.wcs.protos.UpdateResponse value) {
      if (updateResponseBuilder_ == null) {
        if (responseOneofCase_ == 2 &&
            responseOneof_ != one.panda_number.wcs.protos.UpdateResponse.getDefaultInstance()) {
          responseOneof_ = one.panda_number.wcs.protos.UpdateResponse.newBuilder((one.panda_number.wcs.protos.UpdateResponse) responseOneof_)
              .mergeFrom(value).buildPartial();
        } else {
          responseOneof_ = value;
        }
        onChanged();
      } else {
        if (responseOneofCase_ == 2) {
          updateResponseBuilder_.mergeFrom(value);
        } else {
          updateResponseBuilder_.setMessage(value);
        }
      }
      responseOneofCase_ = 2;
      return this;
    }
    /**
     * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
     */
    public Builder clearUpdateResponse() {
      if (updateResponseBuilder_ == null) {
        if (responseOneofCase_ == 2) {
          responseOneofCase_ = 0;
          responseOneof_ = null;
          onChanged();
        }
      } else {
        if (responseOneofCase_ == 2) {
          responseOneofCase_ = 0;
          responseOneof_ = null;
        }
        updateResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
     */
    public one.panda_number.wcs.protos.UpdateResponse.Builder getUpdateResponseBuilder() {
      return getUpdateResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
     */
    @java.lang.Override
    public one.panda_number.wcs.protos.UpdateResponseOrBuilder getUpdateResponseOrBuilder() {
      if ((responseOneofCase_ == 2) && (updateResponseBuilder_ != null)) {
        return updateResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseOneofCase_ == 2) {
          return (one.panda_number.wcs.protos.UpdateResponse) responseOneof_;
        }
        return one.panda_number.wcs.protos.UpdateResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        one.panda_number.wcs.protos.UpdateResponse, one.panda_number.wcs.protos.UpdateResponse.Builder, one.panda_number.wcs.protos.UpdateResponseOrBuilder> 
        getUpdateResponseFieldBuilder() {
      if (updateResponseBuilder_ == null) {
        if (!(responseOneofCase_ == 2)) {
          responseOneof_ = one.panda_number.wcs.protos.UpdateResponse.getDefaultInstance();
        }
        updateResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            one.panda_number.wcs.protos.UpdateResponse, one.panda_number.wcs.protos.UpdateResponse.Builder, one.panda_number.wcs.protos.UpdateResponseOrBuilder>(
                (one.panda_number.wcs.protos.UpdateResponse) responseOneof_,
                getParentForChildren(),
                isClean());
        responseOneof_ = null;
      }
      responseOneofCase_ = 2;
      onChanged();;
      return updateResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:webcamshooting.Response)
  }

  // @@protoc_insertion_point(class_scope:webcamshooting.Response)
  private static final one.panda_number.wcs.protos.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new one.panda_number.wcs.protos.Response();
  }

  public static one.panda_number.wcs.protos.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public one.panda_number.wcs.protos.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

