// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.webcamshooting.PidResponse pid_response = 1;</code>
   * @return Whether the pidResponse field is set.
   */
  boolean hasPidResponse();
  /**
   * <code>.webcamshooting.PidResponse pid_response = 1;</code>
   * @return The pidResponse.
   */
  one.panda_number.wcs.protos.PidResponse getPidResponse();
  /**
   * <code>.webcamshooting.PidResponse pid_response = 1;</code>
   */
  one.panda_number.wcs.protos.PidResponseOrBuilder getPidResponseOrBuilder();

  /**
   * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
   * @return Whether the updateResponse field is set.
   */
  boolean hasUpdateResponse();
  /**
   * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
   * @return The updateResponse.
   */
  one.panda_number.wcs.protos.UpdateResponse getUpdateResponse();
  /**
   * <code>.webcamshooting.UpdateResponse update_response = 2;</code>
   */
  one.panda_number.wcs.protos.UpdateResponseOrBuilder getUpdateResponseOrBuilder();

  public one.panda_number.wcs.protos.Response.ResponseOneofCase getResponseOneofCase();
}
