// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface RespawnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.RespawnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pid = 1;</code>
   * @return The pid.
   */
  java.lang.String getPid();
  /**
   * <code>string pid = 1;</code>
   * @return The bytes for pid.
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>.webcamshooting.Vector3 position = 2;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.webcamshooting.Vector3 position = 2;</code>
   * @return The position.
   */
  one.panda_number.wcs.protos.Vector3 getPosition();
  /**
   * <code>.webcamshooting.Vector3 position = 2;</code>
   */
  one.panda_number.wcs.protos.Vector3OrBuilder getPositionOrBuilder();
}
