// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface UpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.UpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .webcamshooting.PlayerUpdateResponse players = 1;</code>
   */
  java.util.List<one.panda_number.wcs.protos.PlayerUpdateResponse> 
      getPlayersList();
  /**
   * <code>repeated .webcamshooting.PlayerUpdateResponse players = 1;</code>
   */
  one.panda_number.wcs.protos.PlayerUpdateResponse getPlayers(int index);
  /**
   * <code>repeated .webcamshooting.PlayerUpdateResponse players = 1;</code>
   */
  int getPlayersCount();
  /**
   * <code>repeated .webcamshooting.PlayerUpdateResponse players = 1;</code>
   */
  java.util.List<? extends one.panda_number.wcs.protos.PlayerUpdateResponseOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <code>repeated .webcamshooting.PlayerUpdateResponse players = 1;</code>
   */
  one.panda_number.wcs.protos.PlayerUpdateResponseOrBuilder getPlayersOrBuilder(
      int index);
}
