// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package one.panda_number.wcs.protos;

public interface Vector3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:webcamshooting.Vector3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float x = 1;</code>
   * @return The x.
   */
  float getX();

  /**
   * <code>float y = 2;</code>
   * @return The y.
   */
  float getY();

  /**
   * <code>float z = 3;</code>
   * @return The z.
   */
  float getZ();
}
